/**
 * Schema-to-types codegen (DX-2 + DX-8). Introspects the app DB bound as QWIRQ_DB_URL and writes
 * typed bindings for the project's runtime:
 *
 *   node20 (default): `.qwirq/schema.d.ts` — `QwirqDB` map; use as `createBridge<QwirqDB>(url)`.
 *   python312:        `.qwirq/schema.pyi`  — TypedDict stubs for mypy/pyright on `ctx.bridge(table)`.
 *   rust:             `.qwirq/schema.rs`   — serde-compatible structs for typed deserialization.
 *
 * Run with `qwirq types` (binds QWIRQ_DB_URL + QWIRQ_RUNTIME for you) or `npm run types`.
 * Regenerate after schema changes. `.qwirq/` is gitignored — generated, per-schema.
 */
import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs'
import { createBridge } from '@qwirq/bridge'

const pascal = (s: string) => s.replace(/(^|[_-])([a-z0-9])/g, (_, __, c) => c.toUpperCase())

// ---- TS emitter ----
function tsType(dataType: string, nullable: boolean): string {
  let t: string
  switch (dataType) {
    case 'boolean': t = 'boolean'; break
    case 'smallint': case 'integer': case 'real': case 'double precision': t = 'number'; break
    case 'bigint': case 'numeric': case 'money': t = 'string'; break // postgres.js returns these as strings
    case 'json': case 'jsonb': t = 'Record<string, unknown>'; break
    case 'ARRAY': t = 'unknown[]'; break
    default: t = 'string' // text/varchar/uuid/timestamptz/date/time/...
  }
  return nullable ? `${t} | null` : t
}

function emitTs(byTable: Map<string, string[]>): string {
  const tables = [...byTable.keys()].sort()
  // `type` (not `interface`): a type alias satisfies the bridge's `Record<string, Row>` constraint via
  // its implicit index signature; an interface does not, so createBridge<QwirqDB>() would be rejected.
  const ifaces = tables.map((t) => `export type ${pascal(t)} = {\n${byTable.get(t)!.join('\n')}\n}`).join('\n\n')
  const map = `export type QwirqDB = {\n${tables.map((t) => `  ${t}: ${pascal(t)}`).join('\n')}\n}`
  return `// Generated by \`qwirq types\` from the app DB schema. Do not edit; regenerate after schema changes.\n// Use: import type { QwirqDB } from '../.qwirq/schema'; const b = createBridge<QwirqDB>(url)\n\n${ifaces}\n\n${map}\n`
}

// ---- Python emitter (DX-8): TypedDict stubs for mypy/pyright ----
function pyType(dataType: string, nullable: boolean): string {
  let t: string
  switch (dataType) {
    case 'boolean': t = 'bool'; break
    case 'smallint': case 'integer': case 'real': case 'double precision': t = 'float'; break
    case 'bigint': case 'numeric': case 'money': t = 'str'; break // psycopg returns decimals as str
    case 'json': case 'jsonb': t = 'dict[str, object]'; break
    case 'ARRAY': t = 'list[object]'; break
    default: t = 'str'
  }
  return nullable ? `${t} | None` : t
}

function emitPython(byTable: Map<string, string[]>, byTablePy: Map<string, string[]>): string {
  const tables = [...byTable.keys()].sort()
  const classes = tables.map((t) => {
    const fields = byTablePy.get(t)!.join('\n')
    return `class ${pascal(t)}(TypedDict):\n${fields}`
  }).join('\n\n')
  return (
    `# Generated by \`qwirq types\` from the app DB schema. Do not edit; regenerate after schema changes.\n` +
    `# Use: from .qwirq.schema import ${tables.map(pascal).join(', ')}\n` +
    `# ctx.bridge("tickets").first() -> Tickets | None\n` +
    `from __future__ import annotations\n` +
    `from typing import TypedDict\n\n` +
    classes + '\n'
  )
}

// ---- Rust emitter (DX-8): serde structs ----
function rustType(dataType: string, nullable: boolean): string {
  let t: string
  switch (dataType) {
    case 'boolean': t = 'bool'; break
    case 'smallint': t = 'i16'; break
    case 'integer': t = 'i32'; break
    case 'bigint': t = 'i64'; break
    case 'real': t = 'f32'; break
    case 'double precision': t = 'f64'; break
    case 'numeric': case 'money': t = 'String'; break
    case 'json': case 'jsonb': t = 'serde_json::Value'; break
    case 'ARRAY': t = 'Vec<serde_json::Value>'; break
    default: t = 'String'
  }
  return nullable ? `Option<${t}>` : t
}

function emitRust(byTable: Map<string, string[]>, byTableRust: Map<string, string[]>): string {
  const tables = [...byTable.keys()].sort()
  const structs = tables.map((t) => {
    const fields = byTableRust.get(t)!.join('\n')
    return `#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]\npub struct ${pascal(t)} {\n${fields}\n}`
  }).join('\n\n')
  return (
    `// Generated by \`qwirq types\` from the app DB schema. Do not edit; regenerate after schema changes.\n` +
    `// Use: let rows: Vec<Tickets> = serde_json::from_value(ctx.bridge().query_all("SELECT * FROM tickets").await?)?;\n` +
    `#![allow(dead_code, non_snake_case)]\n\n` +
    structs + '\n'
  )
}

async function main() {
  const url = process.env.QWIRQ_DB_URL
  if (!url) { console.error('QWIRQ_DB_URL not set (run `qwirq types`, which binds it)'); process.exit(2) }

  // Read the project runtime from env (set by `qwirq types`) or fall back to qwirq.yaml.
  let runtime = process.env.QWIRQ_RUNTIME ?? ''
  if (!runtime && existsSync('qwirq.yaml')) {
    const yaml = readFileSync('qwirq.yaml', 'utf8')
    const m = yaml.match(/^runtime:\s*(\S+)/m)
    if (m) runtime = m[1]
  }
  if (!runtime) runtime = 'node20'

  const b = createBridge(url)
  try {
    const rows = await b.sql<{ table_name: string; column_name: string; data_type: string; is_nullable: string }>`
      select table_name, column_name, data_type, is_nullable
      from information_schema.columns
      where table_schema = 'public' and table_name not like '\_qwirq\_%'
      order by table_name, ordinal_position`

    const byTable = new Map<string, string[]>()       // TS type lines
    const byTablePy = new Map<string, string[]>()     // Python TypedDict field lines
    const byTableRust = new Map<string, string[]>()   // Rust struct field lines

    for (const r of rows) {
      const nullable = r.is_nullable === 'YES'
      const colKey = /^[A-Za-z_][A-Za-z0-9_]*$/.test(r.column_name) ? r.column_name : JSON.stringify(r.column_name)
      if (!byTable.has(r.table_name)) {
        byTable.set(r.table_name, [])
        byTablePy.set(r.table_name, [])
        byTableRust.set(r.table_name, [])
      }
      byTable.get(r.table_name)!.push(`  ${colKey}: ${tsType(r.data_type, nullable)}`)
      byTablePy.get(r.table_name)!.push(`    ${r.column_name}: ${pyType(r.data_type, nullable)}`)
      byTableRust.get(r.table_name)!.push(`    pub ${r.column_name.replace(/[^a-zA-Z0-9_]/g, '_')}: ${rustType(r.data_type, nullable)},`)
    }

    const tables = [...byTable.keys()].sort()
    mkdirSync('.qwirq', { recursive: true })

    if (runtime === 'python312') {
      writeFileSync('.qwirq/schema.pyi', emitPython(byTable, byTablePy))
      console.log(`wrote .qwirq/schema.pyi (${tables.length} tables: ${tables.join(', ') || '(none yet)'})`)
    } else if (runtime === 'rust') {
      writeFileSync('.qwirq/schema.rs', emitRust(byTable, byTableRust))
      console.log(`wrote .qwirq/schema.rs (${tables.length} tables: ${tables.join(', ') || '(none yet)'})`)
    } else {
      writeFileSync('.qwirq/schema.d.ts', emitTs(byTable))
      console.log(`wrote .qwirq/schema.d.ts (${tables.length} tables: ${tables.join(', ') || '(none yet)'})`)
    }
  } finally {
    await b.close()
  }
}
main().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1) })
