/**
 * Schema-to-types codegen (DX-2). Introspects the app DB bound as QWIRQ_DB_URL and writes
 * `.qwirq/schema.d.ts` — a `QwirqDB` map of table -> row type. Pass it to `createBridge<QwirqDB>(url)` and
 * every `bridge('your_table')` autocompletes its ACTUAL columns and type-checks against the real schema.
 *
 * Run it with `qwirq types` (binds QWIRQ_DB_URL for you) or `npm run types`. Regenerate after schema
 * changes. `.qwirq/` is gitignored — it is generated, per-schema.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { createBridge } from '@qwirq/bridge'

const pascal = (s: string) => s.replace(/(^|[_-])([a-z0-9])/g, (_, __, c) => c.toUpperCase())
function tsType(dataType: string, nullable: boolean): string {
  let t: string
  switch (dataType) {
    case 'boolean': t = 'boolean'; break
    case 'smallint': case 'integer': case 'real': case 'double precision': t = 'number'; break
    case 'bigint': case 'numeric': case 'money': t = 'string'; break // postgres.js returns these as strings
    case 'json': case 'jsonb': t = 'Record<string, unknown>'; break
    case 'ARRAY': t = 'unknown[]'; break
    default: t = 'string' // text/varchar/uuid/timestamptz/date/time/...
  }
  return nullable ? `${t} | null` : t
}

async function main() {
  const url = process.env.QWIRQ_DB_URL
  if (!url) { console.error('QWIRQ_DB_URL not set (run `qwirq types`, which binds it)'); process.exit(2) }
  const b = createBridge(url)
  try {
    const rows = await b.sql<{ table_name: string; column_name: string; data_type: string; is_nullable: string }>`
      select table_name, column_name, data_type, is_nullable
      from information_schema.columns
      where table_schema = 'public' and table_name not like '\_qwirq\_%'
      order by table_name, ordinal_position`
    const byTable = new Map<string, string[]>()
    for (const r of rows) {
      const line = `  ${/^[A-Za-z_][A-Za-z0-9_]*$/.test(r.column_name) ? r.column_name : JSON.stringify(r.column_name)}: ${tsType(r.data_type, r.is_nullable === 'YES')}`
      if (!byTable.has(r.table_name)) byTable.set(r.table_name, [])
      byTable.get(r.table_name)!.push(line)
    }
    const tables = [...byTable.keys()].sort()
    // `type` (not `interface`): a type alias satisfies the bridge's `Record<string, Row>` constraint via
    // its implicit index signature; an interface does not, so createBridge<QwirqDB>() would be rejected.
    const ifaces = tables.map((t) => `export type ${pascal(t)} = {\n${byTable.get(t)!.join('\n')}\n}`).join('\n\n')
    const map = `export type QwirqDB = {\n${tables.map((t) => `  ${t}: ${pascal(t)}`).join('\n')}\n}`
    const banner = `// Generated by \`qwirq types\` from the app DB schema. Do not edit; regenerate after schema changes.\n// Use: import type { QwirqDB } from '../.qwirq/schema'; const b = createBridge<QwirqDB>(url)\n\n`
    mkdirSync('.qwirq', { recursive: true })
    writeFileSync('.qwirq/schema.d.ts', banner + ifaces + '\n\n' + map + '\n')
    console.log(`wrote .qwirq/schema.d.ts (${tables.length} tables: ${tables.join(', ') || '(none yet)'})`)
  } finally {
    await b.close()
  }
}
main().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1) })
